captainVersion: 4
services:
    '$$cap_appname':
        image: linuxserver/wireguard:latest
        environment:
            SERVERURL: '$$cap_appname.$$cap_root_domain'
            PEERS: 2
        volumes:
            - '$$cap_appname-data:/config'
        ports:
            - 5000:5000
            - 51820:51820
        cap_add:
            - NET_ADMIN
        caproverExtra:
            containerHttpPort: '5000'
caproverOneClickApp:
    variables:
        - id: '$$cap_version'
          label: PrivateBin Version
          defaultValue: '1.3.4'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/privatebin/nginx-fpm-alpine/tags
          validRegex: "/^([^\\s^\\/])+$/"
        - id: '$$cap_tz'
          label: Time Zone
          defaultValue: America/New_York
          description: Get yours from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
          validRegex: '/.{1,}/'
    instructions:
        start: |-
            Wireguard!
        end: |-
            Wireguard has been successfully deployed!
    displayName: WireGuard
    isOfficial: false
    description: It's wireguard
    documentation: See https://github.com/PrivateBin/docker-nginx-fpm-alpine
